name: Build and Deploy to Azure Web App

on:
  push:
    branches: ["master"]

env:
  AZURE_WEBAPP_NAME: 'selu383-sp25-p03-g04'   # your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: './publish'      # path to the output directory
  DOTNET_VERSION: '9.0.x'                     # .NET version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish Selu383.SP25.P03.Api/Selu383.SP25.P03.Api.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:

        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
